<a href="https://colab.research.google.com/github/codedyasai/Python_Intermediate/blob/main/disorder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [77]:
disorder = pd.read_excel('disorder.xlsx', index_col=[0,1,2,3],header=[0,1,2],sheet_name = 5)
disorder

                      2018년                                                  \
                       ADHD                   비만                  불면증
연령구분                 요양급여비용 입내원일수   환자수   요양급여비용 입내원일수 환자수     요양급여비용 입내원일수
서울 강남구 남 0~9세     188836790  3330   437  9914070   121  57          0     0
         10~19세   563498480  8869  1111  9030550   130  63    9071590   214
         20~29세   213248290  3485   456  5063090    62  34   80715840  2655
         30~39세    72761750  1357   174  3278370    79  41  111038700  4220
         40~49세    21611080   357    55  1528400    51  31   95899090  3199
...                     ...   ...   ...      ...   ...  ..        ...   ...
세종 세종시 여 60~69세           0     0     0        0     0   0   10201290   509
         70~79세           0     0     0        0     0   0    5933020   379
         80~89세           0     0     0        0     0   0   15137740   408
         90~99세           0     0     0        0     0   0     548430    35
         100세 이상          0     0     0        0     0   0          0     0

                                   ... 2022년                           \
                             불안장애  ...  불안장애         우울증
연령구분               환자수     요양급여비용  ...   환자수      요양급여비용  입내원일수   환자수
서울 강남구 남 0~9세        0    3386480  ...    32    14977490    104    29
         10~19세     93   91139760  ...   381   715996250   7525   902
         20~29세    845  378874120  ...  1470  2194649860  20737  2578
         30~39세   1236  415359940  ...  1700  1988843730  18796  2644
         40~49세    959  398495180  ...  1666  1279850000  13217  1934
...                ...        ...  ...   ...         ...    ...   ...
세종 세종시 여 60~69세    172   37857700  ...   397   176751500   3240   522
         70~79세    119   46748290  ...   259    95748080   1959   292
         80~89세     77   11629650  ...   126    32449070    743   131
         90~99세     15          0  ...    11           0      0     0
         100세 이상     0          0  ...     0           0      0     0


                        조울증                   조현병
연령구분                 요양급여비용 입내원일수  환자수     요양급여비용 입내원일수  환자수
서울 강남구 남 0~9세       9653770   155   20          0     0    0
         10~19세   187028170  1504  187   54353060   306   36
         20~29세   573151310  5357  664  208020460  1754  188
         30~39세   327025620  3155  443  239147050  2512  225
         40~49세   191300150  1910  278  263874340  2857  266
...                     ...   ...  ...        ...   ...  ...
세종 세종시 여 60~69세    14512840   230   32   40381390   597   29
         70~79세     5695080   113   15   39400730   550   13
         80~89세     2291230    29   10          0     0    0
         90~99세           0     0    0          0     0    0
         100세 이상          0     0    0          0     0    0

[5500 rows x 105 columns]

In [84]:
disorder.loc[('서울','강남구','남'),('2018년','ADHD','입내원일수')]['0~9세']

<ipython-input-84-380d138c713a>:1: PerformanceWarning: indexing past lexsort depth may impact performance.
  disorder.loc[('서울','강남구','남'),('2018년','ADHD','입내원일수')]['0~9세']

3330